### ISSUE TITLE
`Error: invalid command name 'setup.py'`

### ISSUE THREAD

**Issue by iftahnaf** [abichinger/semantic-release-pypi#25]
Hi,

I have a problem running my CI, it failed with the error:
```
errors: [
    Error: invalid command name 'setup.py'
        at verifySetupPy (/opt/hostedtoolcache/node/18.17.1/x[64](https://github.com/iftahnaf/pyvectorguidance/actions/runs/6321915420/job/17166635003#step:8:65)/lib/node_modules/semantic-release-pypi/lib/verify.js:43:15)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async verify (/opt/hostedtoolcache/node/18.17.1/x64/lib/node_modules/semantic-release-pypi/lib/verify.js:94:5)
        at async validator (file:///opt/hostedtoolcache/node/18.17.1/x64/lib/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
        at async file:///opt/hostedtoolcache/node/18.17.1/x64/lib/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
        at async Promise.all (index 0)
        at async next (file:///opt/hostedtoolcache/node/18.17.1/x64/lib/node_modules/semantic-release/node_modules/p-reduce/index.js:15:44) {
      pluginName: 'semantic-release-pypi'
```

my `release.yml`:

```yaml
name: Release

on: 
  push:
    branches: 
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/github @semantic-release/commit-analyzer @semantic-release/git @semantic-release/release-notes-generator semantic-release-pypi
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
      - name: Install setuptools
        run: python -m pip install --upgrade setuptools wheel twine
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: npx semantic-release
    permissions:
      contents: write

```

and the `.release.json`:
```json
{
  "branches": ["main"],
  "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
          "semantic-release-pypi",
          {
            "repoUrl": "https://upload.pypi.org/legacy/"
          }
      ],
      "@semantic-release/github",
      [
          "@semantic-release/git",
          {
              "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
              "assets": ["CHANGELOG.md", "setup.py", "setup.cfg"]
          }
      ]
  ]
}
```

Any ideas on how to solve this issue?

Thanks in advance!
